services:
  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./public:/app/public
      - ./lib:/app/lib
      - ./contexts:/app/contexts
      - ./content:/app/content
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
